
 
 
 
// —————————————— 
// <auto-generated> 
//	This code was auto-generated 07/11/2024 15:38:31
//     	T4 template generates dbcontext context and concurrency code
//	NOTE:T4 generated code may need additional updates/addjustments by developer in order to compile a solution.
// <auto-generated> 
// —————————————–

using System;
using System.Threading.Tasks;
using System.Linq;
using System.Configuration;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
namespace AssetManagementProject.web.Entity.Context
{
    public partial class DefaultDbContext : DbContext
    {
	
		public DbSet<Asset> Assets { get; set; }
	
		public DbSet<Category> Categorys { get; set; }
	
		public DbSet<AssetClass> AssetClasss { get; set; }
	
		public DbSet<AssetMaintenance> AssetMaintenances { get; set; }

		/// Add new entities concurrency declarations (Fluent API)
		partial void SetAdditionalConcurency(ModelBuilder modelBuilder)
		{
			modelBuilder.Entity<Asset>().Property(a => a.RowVersion).IsRowVersion();
			modelBuilder.Entity<Category>().Property(a => a.RowVersion).IsRowVersion();
			modelBuilder.Entity<AssetClass>().Property(a => a.RowVersion).IsRowVersion();
			modelBuilder.Entity<AssetMaintenance>().Property(a => a.RowVersion).IsRowVersion();
   
		}
	}
}

