

 
 
 
// —————————————— 
// <auto-generated> 
//	This code was auto-generated 07/11/2024 15:38:41 
//	T4 template generates viewmodel's code 
//	NOTE:T4 generated code may need additional updates/addjustments by developer in order to compile a solution.
// <auto-generated> 
// —————————————–
using System;
using System.Collections.Generic;
namespace AssetManagementProject.web.Domain
{

    /// <summary>
    ///
    /// A Asset view model
    ///   
    ///       MANUAL UPDATES REQUIRED! 
    ///       NOTE use PM console to update database with new entity : 
    ///            PM>add-migration AddAsset
    ///            PM>update-database
    ///
    /// </summary>
    public partial class AssetViewModel : BaseDomain
    {
	  		public string Name { get; set; } 
			public string Description { get; set; } 
			public bool IsActive { get; set; } 
			public int CategoryId { get; set; } 
			public int ClassId { get; set; } 
			public virtual CategoryViewModel Category { get; set; } 
			public virtual AssetClassViewModel AssetClass { get; set; } 
	} 
	
    /// <summary>
    ///
    /// A Category view model
    ///   
    ///       MANUAL UPDATES REQUIRED! 
    ///       NOTE use PM console to update database with new entity : 
    ///            PM>add-migration AddCategory
    ///            PM>update-database
    ///
    /// </summary>
    public partial class CategoryViewModel : BaseDomain
    {
	  		public string Name { get; set; } 
			public string Description { get; set; } 
	} 
	
    /// <summary>
    ///
    /// A AssetClass view model
    ///   
    ///       MANUAL UPDATES REQUIRED! 
    ///       NOTE use PM console to update database with new entity : 
    ///            PM>add-migration AddAssetClass
    ///            PM>update-database
    ///
    /// </summary>
    public partial class AssetClassViewModel : BaseDomain
    {
	  		public string Name { get; set; } 
			public string Description { get; set; } 
	} 
	
    /// <summary>
    ///
    /// A AssetMaintenance view model
    ///   
    ///       MANUAL UPDATES REQUIRED! 
    ///       NOTE use PM console to update database with new entity : 
    ///            PM>add-migration AddAssetMaintenance
    ///            PM>update-database
    ///
    /// </summary>
    public partial class AssetMaintenanceViewModel : BaseDomain
    {
	  		public int AssetId { get; set; } 
			public string Location { get; set; } 
			public decimal Cost { get; set; } 
			public string Status { get; set; } 
			public System.DateTime LastMaintenanceDate { get; set; } 
			public System.DateTime NextMaintenanceDate { get; set; } 
			public virtual AssetViewModel Asset { get; set; } 
	} 
	     
}