
 
 
 
// —————————————— 
// <auto-generated> 
//	This code was auto-generated 07/11/2024 15:38:51 
//	T4 template generates viewmodel mapping profile code 
//	NOTE:T4 generated code may need additional updates/addjustments by developer in order to compile a solution.
// <auto-generated> 
// —————————————–
using System;
using System.Collections.Generic;
using System.Text;
using AutoMapper;
using AssetManagementProject.web.Entity;
namespace AssetManagementProject.web.Domain.Mapping
{
    /// <summary>
    /// 
    /// </summary>
    public partial class MappingProfile : Profile
    {
        partial void SetAddedMappingProfile()
        {
    			CreateMap<AssetViewModel, Asset>();
			CreateMap<Asset, AssetViewModel>();
				CreateMap<CategoryViewModel, Category>();
			CreateMap<Category, CategoryViewModel>();
				CreateMap<AssetClassViewModel, AssetClass>();
			CreateMap<AssetClass, AssetClassViewModel>();
				CreateMap<AssetMaintenanceViewModel, AssetMaintenance>();
			CreateMap<AssetMaintenance, AssetMaintenanceViewModel>();
	 
		}	
	} 
}

